### ISSUE TITLE
Panic when using the library from an imgui-rs based application

### ISSUE THREAD

**Issue by rgiot** [EmbarkStudios/nfd2#6]
**Describe the bug**
`imgui` (https://github.com/Gekkio/imgui-rs/) does not provide a file picker. So I gave a try to `nfd2`. The following piece of code (included in the definition of a window)
```rust
...
        if ui.small_button(im_str!("...")) {
            if let Ok(nfd2::Response::Okay(fname)) = nfd2::open_file_dialog(
                Some("bmp,png,jpg"), 
                None)
            {
                state.texture_import = fname.into();
            }
        }
...
```
makes panic the application.

The same code in a standalone application that does not use imgui-rs works perfectly.
The issue exists also with the original `nfd`crate.

I have no idea if I have to report the bug there (I guess) or in ìmgui-rs` repository.

**Expected behavior**
No panic is expected.

**Trace**
```
thread 'main' panicked at 'already mutably borrowed: BorrowError', /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\cell.rs:798
:9
stack backtrace:
   0: core::fmt::write
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\fmt\mod.rs:1069
   1: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\io\mod.rs:1427
   2: std::sys_common::backtrace::_print
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys_common\backtrace.rs:62
   3: std::sys_common::backtrace::print
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\sys_common\backtrace.rs:49
   4: std::panicking::default_hook::{{closure}}
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:198
   5: std::panicking::default_hook
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:218
   6: std::panicking::rust_panic_with_hook
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:511
   7: std::panicking::begin_panic_handler
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libstd\panicking.rs:419
   8: core::panicking::panic_fmt
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\panicking.rs:111
   9: core::option::expect_none_failed
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\/src\libcore\option.rs:1211
  10: core::result::Result<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>,
 core::cell::BorrowError>::expect<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\result.rs:961
  11: core::cell::RefCell<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>::borrow<core::opt
ion::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa\src\libcore\cell.rs:798
  12: NtGdiExtSelectClipRgn
  13: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\giotr\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:104
  14: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\giotr\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.21.0\src\platform_impl\windows\event_loop.rs:1382
  15: DefSubclassProc
  16: DefSubclassProc
  17: AddClipboardFormatListener
  18: GetParent
  19: CallWindowProcW
  20: glDebugEntry
  21: AddClipboardFormatListener
  22: GetParent
  23: GetParent
  24: IsRectEmpty
  25: KiUserCallbackDispatcher
  26: <unknown>
  27: DllGetClassObject
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: AddClipboardFormatListener
  32: PtInRect
  33: PtInRect
  34: PtInRect
  35: AddClipboardFormatListener
  36: GetParent
  37: GetParent
  38: IsRectEmpty
  39: KiUserCallbackDispatcher
  40: IsWindow
  41: DialogBoxIndirectParamAorW
  42: DialogBoxIndirectParamAorW
  43: DialogBoxIndirectParamW
  44: DllCanUnloadNow
  45: <unknown>
  46: NFD_OpenDialog
             at C:\Users\giotr\.cargo\registry\src\github.com-1ecc6299db9ec823\nfd2-0.1.1\nativefiledialog\src\nfd_win.cpp:426
  47: nfd2::open_dialog
             at C:\Users\giotr\.cargo\registry\src\github.com-1ecc6299db9ec823\nfd2-0.1.1\src\lib.rs:176
  48: nfd2::open_file_dialog
             at C:\Users\giotr\.cargo\registry\src\github.com-1ecc6299db9ec823\nfd2-0.1.1\src\lib.rs:121
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\magicrasters.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Device:**
 - OS: Window10
 - Version: 0.2.0 and 0.1.1 (not tested with previous one)

**Comment by Jake-Shadle** [comment]
Looking at the callstack, it's not imgui that is the issue, but winit. We use this library in an internal project that also uses imgui and winit, but have not seen this problem to my knowledge, but that's likely due to us using a fairly old fork of winit with some other bug fixes.

I would file this issue against the winit repo.
